package
{
   public class CurveData
   {
       
      
      public var pencilMoreGames:*;
      
      private var main:*;
      
      public var twitterIcon:*;
      
      public var pencilWalkthrough:*;
      
      public var pencilHighScores:*;
      
      public var rubberStart:*;
      
      public var pencilAddGame:*;
      
      public var pencilInstructions:*;
      
      public var pencilSelectLevel:*;
      
      public var facebookIcon:*;
      
      public function CurveData(param1:*)
      {
         this.facebookIcon = {
            "pointer":0.13902,
            "keys":[{
               "pos":{
                  "x":743.79999,
                  "y":37.84999
               },
               "c2":{
                  "x":-68.96683,
                  "y":-0.03684
               },
               "rcp":false,
               "c1":{
                  "x":64.87466,
                  "y":0.03465
               }
            },{
               "pos":{
                  "x":453.04998,
                  "y":38.04998
               },
               "c2":{
                  "x":-58.8748,
                  "y":0.32936
               },
               "rcp":false,
               "c1":{
                  "x":71.5,
                  "y":-0.4
               }
            }],
            "cid":null,
            "mapx":266.79998,
            "obj":"facebookicon.swf",
            "duration":1.39999,
            "mapy":-12.2,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.twitterIcon = {
            "pointer":0.09024,
            "keys":[{
               "pos":{
                  "x":805.79999,
                  "y":36.84999
               },
               "c2":{
                  "x":-68.96683,
                  "y":-0.03684
               },
               "rcp":false,
               "c1":{
                  "x":64.87466,
                  "y":0.03465
               }
            },{
               "pos":{
                  "x":515.04998,
                  "y":37.04998
               },
               "c2":{
                  "x":-58.8748,
                  "y":0.32936
               },
               "rcp":false,
               "c1":{
                  "x":71.5,
                  "y":-0.4
               }
            }],
            "cid":null,
            "mapx":266.79998,
            "obj":"twittericon.swf",
            "duration":1.39999,
            "mapy":-12.2,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.rubberStart = {
            "pointer":0.0878,
            "keys":[{
               "pos":{
                  "x":747.79999,
                  "y":105.69999
               },
               "c2":{
                  "x":-46.99805,
                  "y":2.0323
               },
               "rcp":false,
               "c1":{
                  "x":66.1472,
                  "y":-2.86035
               }
            },{
               "pos":{
                  "x":421.04998,
                  "y":140.04998
               },
               "c2":{
                  "x":-58.48813,
                  "y":6.7445699999999995
               },
               "rcp":false,
               "c1":{
                  "x":55.5,
                  "y":-6.4
               }
            }],
            "cid":null,
            "mapx":266.79998,
            "obj":"rubberstart.swf",
            "duration":1.39999,
            "mapy":-12.2,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.pencilInstructions = {
            "pointer":0.36097,
            "keys":[{
               "pos":{
                  "x":1242.09999,
                  "y":204.55
               },
               "c2":{
                  "x":-108.04805,
                  "y":7.0323
               },
               "rcp":false,
               "c1":{
                  "x":66.06923,
                  "y":-4.30011
               }
            },{
               "pos":{
                  "x":720.14999,
                  "y":233.64999
               },
               "c2":{
                  "x":-58.77902,
                  "y":3.37315
               },
               "rcp":false,
               "c1":{
                  "x":122.85,
                  "y":-7.05
               }
            }],
            "cid":null,
            "mapx":147.39999,
            "obj":"instructions.swf",
            "duration":1.4,
            "mapy":31.4,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.pencilSelectLevel = {
            "pointer":0.72804,
            "keys":[{
               "pos":{
                  "x":1199.04999,
                  "y":287
               },
               "c2":{
                  "x":-115.04804,
                  "y":3.03229
               },
               "rcp":false,
               "c1":{
                  "x":66.18603,
                  "y":-1.74445
               }
            },{
               "pos":{
                  "x":720.79999,
                  "y":291.84998
               },
               "c2":{
                  "x":-58.87361,
                  "y":0.49913
               },
               "rcp":false,
               "c1":{
                  "x":123.85,
                  "y":-1.05
               }
            }],
            "cid":null,
            "mapx":106.79998,
            "obj":"selectlevel.swf",
            "duration":1.39999,
            "mapy":-8.2,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.pencilWalkthrough = {
            "pointer":0.94146,
            "keys":[{
               "pos":{
                  "x":1211.04999,
                  "y":285
               },
               "c2":{
                  "x":-24.99804,
                  "y":2.03229
               },
               "rcp":false,
               "c1":{
                  "x":65.99129,
                  "y":-5.36498
               }
            },{
               "pos":{
                  "x":720.29998,
                  "y":319.24998
               },
               "c2":{
                  "x":-58.68454,
                  "y":4.74089
               },
               "rcp":false,
               "c1":{
                  "x":22.9,
                  "y":-1.85
               }
            }],
            "cid":null,
            "mapx":262.79998,
            "obj":"walkthrough.swf",
            "duration":1.39999,
            "mapy":-10.2,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.pencilHighScores = {
            "pointer":1,
            "keys":[{
               "pos":{
                  "x":1214.04999,
                  "y":312
               },
               "c2":{
                  "x":-24.99804,
                  "y":2.03229
               },
               "rcp":false,
               "c1":{
                  "x":65.99129,
                  "y":-5.36498
               }
            },{
               "pos":{
                  "x":722.29998,
                  "y":362.24998
               },
               "c2":{
                  "x":-58.68454,
                  "y":4.74089
               },
               "rcp":false,
               "c1":{
                  "x":22.9,
                  "y":-1.85
               }
            }],
            "cid":null,
            "mapx":50.79998,
            "obj":"highscores.swf",
            "duration":1.39999,
            "mapy":-5.2,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.pencilMoreGames = {
            "pointer":0.23048,
            "keys":[{
               "pos":{
                  "x":1230.79999,
                  "y":435.8
               },
               "c2":{
                  "x":-32.99805,
                  "y":-2.96769
               },
               "rcp":false,
               "c1":{
                  "x":65.94286,
                  "y":5.93061
               }
            },{
               "pos":{
                  "x":720.29998,
                  "y":419.24998
               },
               "c2":{
                  "x":-58.81924,
                  "y":-2.57837
               },
               "rcp":false,
               "c1":{
                  "x":36.5,
                  "y":1.59999
               }
            }],
            "cid":null,
            "mapx":266.79998,
            "obj":"moregames.swf",
            "duration":1.39999,
            "mapy":-12.2,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         this.pencilAddGame = {
            "pointer":0.02439,
            "keys":[{
               "pos":{
                  "x":774.04999,
                  "y":475.94999
               },
               "c2":{
                  "x":-115.08235,
                  "y":1.13948
               },
               "rcp":false,
               "c1":{
                  "x":75.18602,
                  "y":-0.74445
               }
            },{
               "pos":{
                  "x":247.74999,
                  "y":475.79998
               },
               "c2":{
                  "x":-58.87553,
                  "y":0.1483
               },
               "rcp":false,
               "c1":{
                  "x":19.84999,
                  "y":-0.05
               }
            }],
            "cid":null,
            "mapx":-121.65001,
            "obj":"addgame.swf",
            "duration":1.39999,
            "mapy":47,
            "selectedChannel":"time",
            "map":"openscreen.swf",
            "chns":[{
               "name":"time",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.42073,
                     "y":0.82142
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.56463,
                     "y":0.91964
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":0.6939,
                     "y":0.98214
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"rotation",
               "yFactor":360,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"scale",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"z",
               "yFactor":10,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":0.1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            },{
               "name":"alpha",
               "yFactor":1,
               "keys":[{
                  "pos":{
                     "x":0,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               },{
                  "pos":{
                     "x":1,
                     "y":1
                  },
                  "c2":{
                     "x":0,
                     "y":0
                  },
                  "rcp":true,
                  "c1":{
                     "x":0,
                     "y":0
                  }
               }]
            }]
         };
         super();
         this.main = param1;
      }
   }
}
